plot_theme <- theme(legend.position = "none", ##Create plot theme
                    legend.title = element_text(size = 6, colour = "black", face = "bold"),
                    legend.text = element_text(size = 5, colour = "black"),
                    legend.background = element_rect(fill = NA),
                    legend.key.size = unit(0.2, "cm"),
                    legend.key = element_blank(),
                    axis.line.x =  element_line(color = "black", size = 0.25),
                    axis.line.y = element_line(color = "black", size = 0.25),
                    axis.ticks = element_line(color = "black", size = 0.25),
                    panel.grid.major.y =  element_line(color = "grey40", size = 0.1),
                    panel.grid.major.x =  element_blank(),
                    panel.grid.minor = element_blank(),
                    panel.border = element_blank(),
                    panel.background = element_blank(),
                    axis.title.x = element_text( face = "bold", size = 7, colour = "black"),
                    axis.text.x = element_text( size = 6, colour = "black"),
                    axis.title.y = element_text( face = "bold", size = 7, colour = "black"),
                    axis.text.y = element_text( size = 6, colour = "black"),
                    plot.margin = unit(c(0, 3, 0, 0), "mm"),
                    strip.text.x = element_text( size = 7, face = "bold", colour = "black", margin = margin(0, 0, 1, 0, "mm")),
                    strip.text.y = element_text( size = 7, face = "bold", colour = "black", margin = margin(0, 0, 1, 0, "mm")),
                    strip.background = element_rect(color = NA, fill = NA))
